### ISSUE TITLE
Modify ReadMe.md file

### ISSUE THREAD

**Issue by Sejal-16** [PCCoE-Hacktoberfest-21/FRIDAY#18]
![image](https://user-images.githubusercontent.com/65293021/135717663-49157a66-16c6-4dca-8345-c5194fd9ffc9.png)

Can we have something like this to this repo's readme file displaying maintainers?
Also we can have a connect with us section in this file at the end . Maintainers  bio , their github link , maybe some other social media links also can be included.

**Comment by Sejal-16** [comment]
I would like to work on it.

**Comment by rohitjoshi6** [comment]
> I would like to work on it.

Hey @Sejal-16 . Go ahead. 
I am assigning you this issue

**Comment by Sejal-16** [comment]
Thanks:)

**Comment by Sejal-16** [comment]
Hey i have done some changes they look like this : 
![image](https://user-images.githubusercontent.com/65293021/135730812-aa5643fd-8024-4f2d-915c-be3182a96c1e.png)

Can i go ahead and make a pull request?
Additionally we can your bio and social media links too. Let me know.

**Comment by rohitjoshi6** [comment]
> Hey i have done some changes they look like this : ![image](https://user-images.githubusercontent.com/65293021/135730812-aa5643fd-8024-4f2d-915c-be3182a96c1e.png)
> 
> If someone clicks on your image , they will be redirected to your github profile and if clicked on your name then on your linkedIn profile. Can i go ahead and make a pull request? Additionally we can your bio and social media links too. Let me know.

Awesome work @Sejal-16 . Go ahead and make a PR
