### ISSUE TITLE
Whats trending?

### ISSUE THREAD

**Issue by harshadbhere** [PCCoE-Hacktoberfest-21/FRIDAY#22]
Tell user what is currently trending

**Comment by harshadbhere** [comment]
@rohitjoshi6 can I work on this?

**Comment by rohitjoshi6** [comment]
Hey @harshadbhere Go ahead . I am assigning this issue to you.

**Comment by harshadbhere** [comment]
Hey @rohitjoshi6 , how can I give audio input?

**Comment by rohitjoshi6** [comment]
> Hey @rohitjoshi6 , how can I give audio input?

I am attaching the function which takes audio input from user:
![image](https://user-images.githubusercontent.com/56406787/135755979-d4507ed4-aaae-47b7-9668-7be2f266762b.png)

**Comment by harshadbhere** [comment]
@rohitjoshi6 thanks for this but my query is different. I meant how can I give user input when the program is running? Am I supposed to speak into microphone?

**Comment by rohitjoshi6** [comment]
> @rohitjoshi6 thanks for this but my query is different. I meant how can I give user input when the program is running? Am I supposed to speak into microphone?

Yup there's a while loop during which you are supposed to give command in your microphone .

**Comment by harshadbhere** [comment]
> Yup there's a while loop during which you are supposed to give command in your microphone .
I tried it but the input is not  getting detected

**Comment by rohitjoshi6** [comment]
> > Yup there's a while loop during which you are supposed to give command in your microphone .
> 
> I tried it but the input is not getting detected

Try checking your microphone permissions , that might be causing the issue

**Comment by harshadbhere** [comment]
@rohitjoshi6 nvm, I resolved it! Adding noise cancellation in get_audio :)
