### ISSUE TITLE
Error for playsound "The specified device is not open or is not recognized by MCI"

### ISSUE THREAD

**Issue by harshadbhere** [PCCoE-Hacktoberfest-21/FRIDAY#27]
Everytime I try to run the program, I am greeted by this error. Any possible solution for this problem?

**Comment by rohitjoshi6** [comment]
There's a solution where you can downgrade your python version to 3.7 or 3.8
I find some other solution , I will let you know

**Comment by harshadbhere** [comment]
@rohitjoshi6 already tried! Downgrading did not resolve the issue :(
An alternate solution is to use the lib pysttx3 in place of playsound

**Comment by rohitjoshi6** [comment]
> @rohitjoshi6 already tried! Downgrading did not resolve the issue :( An alternate solution is to use the lib pysttx3 in place of playsound

Changing from gtts to pyttsx at this moment is not suitable because there are various people working on same issue.
I will look for an alternative
