### ISSUE TITLE
Search for location!

### ISSUE THREAD

**Issue by vaishnavigaikwad** [PCCoE-Hacktoberfest-21/FRIDAY#31]
If the user wants to Search for Location, he/she can ask the assistant “Hey Friday! where is Pune?”

**Comment by vaishnavigaikwad** [comment]
> If the user wants to Search for Location, he/she can ask the assistant “Hey Friday! where is Pune?”

Can I work on this issue ?

**Comment by rohitjoshi6** [comment]
@vaishnavigaikwad there's a similar existing issue . You can check it out over here #3
