### ISSUE TITLE
Random qoute

### ISSUE THREAD

**Issue by harshadbhere** [PCCoE-Hacktoberfest-21/FRIDAY#32]
Tell the user a random quote whenever he asks for it

**Comment by harshadbhere** [comment]
Can I work on this?

**Comment by rohitjoshi6** [comment]
Go ahead @harshadbhere

**Comment by EFFLUX110** [comment]
@rohitjoshi6 check this [pull request](https://github.com/PCCoE-Hacktoberfest-21/FRIDAY/pull/46)
