### ISSUE TITLE
Searching Something on Google

### ISSUE THREAD

**Issue by BAHETIHARSH** [PCCoE-Hacktoberfest-21/FRIDAY#47]
It will open the web browser and ask for what do you want to search on google.

**Comment by rohitjoshi6** [comment]
Go ahead @BAHETIHARSH

**Comment by ChetansMittal** [comment]
I want to work on these isse 
I can do it easit made it before 
It can searcha anything on google

**Comment by rohitjoshi6** [comment]
Hi @jyotijangid @ChetansMittal , 
Currently @BAHETIHARSH is working on this issue 
You can open a new issue if you want to add a new feature [over here](https://github.com/PCCoE-Hacktoberfest-21/FRIDAY/issues)
