### ISSUE TITLE
Dictate Covid-19 stats to user

### ISSUE THREAD

**Issue by rohitjoshi6** [PCCoE-Hacktoberfest-21/FRIDAY#5]
### Example:

User: What is number of current active cases of Covid-19 in {country-name} ?
FRIDAY(Voice Assistant) : The current active cases in {country-name} are {insert a number here}

**Comment by Kishore-abhimanyu** [comment]
Can you assign me to this?

**Comment by rohitjoshi6** [comment]
> Can you assign me to this?

Hi Kishor ! Go ahead

**Comment by Kishore-abhimanyu** [comment]
Submitted pull request, please merge
