### ISSUE TITLE
Tell jokes to user

### ISSUE THREAD

**Issue by rohitjoshi6** [PCCoE-Hacktoberfest-21/FRIDAY#6]
### Example:

User: Hey, tell me a joke
FRIDAY(Voice assistant) : {Insert a joke here}

**Comment by Pranjalmishra30** [comment]
Hey, i would like to work on this issue.
Also i feel we should add a `requirements.txt` file.
Thanks :)

**Comment by rohitjoshi6** [comment]
> Hey, i would like to work on this issue. Also i feel we should add a `requirements.txt` file. Thanks :)

Hey @Pranjalmishra30 thanks a lot for bringing my attention to it .

**Comment by Pranjalmishra30** [comment]
Could you assign this issue to me so i can start working on it.

**Comment by rohitjoshi6** [comment]
> Could you assign this issue to me so i can start working on it.

Yup . Assigning this to you
