### ISSUE TITLE
Tell weather details to User

### ISSUE THREAD

**Issue by rohitjoshi6** [PCCoE-Hacktoberfest-21/FRIDAY#7]
### Example:

User : How is the weather today?
FRIDAY(Voice assistant) : The temperature today is X °C  etc.

**Comment by zatch3301** [comment]
Hi can i work on this one?

**Comment by rohitjoshi6** [comment]
> Hi can i work on this one?

Yes for sure!! Go ahead

**Comment by Animesh312** [comment]
Hi can I work on this issue

**Comment by rohitjoshi6** [comment]
> Hi can I work on this issue

hello @Animesh312 this task is assigned to someone else . 
You can check out other issues [over here](https://github.com/PCCoE-Hacktoberfest-21/FRIDAY/issues)

**Comment by ChetansMittal** [comment]
Hey I want to work on it

**Comment by BAHETIHARSH** [comment]
Can you assign this to me?

**Comment by rohitjoshi6** [comment]
@zatch3301 I am un-assigning you from this issue, as it's been 25+ days.

**Comment by rohitjoshi6** [comment]
@BAHETIHARSH go ahead
