### ISSUE TITLE
Open notepad and write the commands given by the user

### ISSUE THREAD

**Issue by rohitjoshi6** [PCCoE-Hacktoberfest-21/FRIDAY#8]
### Example:

User: open notepad
FRIDAY(Voice assistant) : Yes , opening notepad. What would you like me to write in it?
User : Work on project (user wants to write this in notepad)
FRIDAY (Voice assistant) : [writes the above message in the notepad]

**Comment by RahulPalve** [comment]
hey, Instead of opening notepad can i directly write to file and save it

**Comment by rohitjoshi6** [comment]
> hey, Instead of opening notepad can i directly write to file and save it

Hi @RahulPalve  ! Go ahead and try doing it ! should i assign this issue to you?

**Comment by RahulPalve** [comment]
@rohitjoshi6 https://github.com/PCCoE-Hacktoberfest-21/FRIDAY/pull/10 Done
