### ISSUE TITLE
Wish the user according to time 

### ISSUE THREAD

**Issue by S3raj** [PCCoE-Hacktoberfest-21/FRIDAY#9]
# Example 
Good morning master 
Good evening master

**Comment by S3raj** [comment]
Hey ....can I work on this issue

**Comment by rohitjoshi6** [comment]
> Hey ....can I work on this issue

yes suraj ! Go ahead

**Comment by S3raj** [comment]
> > Hey ....can I work on this issue
> 
> yes suraj ! Go ahead

Yes working on it !

**Comment by Rohit14kvs** [comment]
assign me this issue, i resolve this already

**Comment by rohitjoshi6** [comment]
> assign me this issue, i resolve this already

This issue is already assigned to someone else. 
You can create a issue for new feature that you want to add.

**Comment by ChetansMittal** [comment]
Hey I want to work on it
