### ISSUE TITLE
What can you do

### ISSUE THREAD

**Issue by BAHETIHARSH** [PCCoE-Hacktoberfest-21/FRIDAY#92]
If the user asks what can assistant do for me then the assistant should replay all his features such as 
"I can open application, close application, suggest you a movie, play music, taking photos and all"

**Comment by rohitjoshi6** [comment]
@BAHETIHARSH isnt this is a bit similar to #89

**Comment by BAHETIHARSH** [comment]
In #89 it ask for remembering but in current issue it like for new user if you are new to assistant and you don't know about it's functionalities so it can remind you

**Comment by rohitjoshi6** [comment]
Alright so assistant will tell the uses all the abilities it possesses. Am I ryt?

**Comment by BAHETIHARSH** [comment]
Yes
